In [7]:
import sys
!{sys.executable} -m pip install cpi

Collecting cpi
  Downloading cpi-1.0.5-py2.py3-none-any.whl (28.9 MB)
     |████████████████████████████████| 28.9 MB 3.2 MB/s eta 0:00:01
Requirement already satisfied: python-dateutil in /Users/michaelsmith/opt/anaconda3/lib/python3.9/site-packages (from cpi) (2.8.2)
Requirement already satisfied: click in /Users/michaelsmith/opt/anaconda3/lib/python3.9/site-packages (from cpi) (8.0.3)
Requirement already satisfied: requests in /Users/michaelsmith/opt/anaconda3/lib/python3.9/site-packages (from cpi) (2.23.0)
Requirement already satisfied: pandas in /Users/michaelsmith/opt/anaconda3/lib/python3.9/site-packages (from cpi) (1.3.4)
Requirement already satisfied: pytz>=2017.3 in /Users/michaelsmith/opt/anaconda3/lib/python3.9/site-packages (from pandas->cpi) (2021.3)
Requirement already satisfied: numpy>=1.17.3 in /Users/michaelsmith/opt/anaconda3/lib/python3.9/site-packages (from pandas->cpi) (1.20.3)
Requirement already satisfied: six>=1.5 in /Users/michaelsmith/opt/anaconda3/lib/python3.9/site-packages (from python-dateutil->cpi) (1.16.0)
Requirement already satisfied: chardet<4,>=3.0.2 in /Users/michaelsmith/opt/anaconda3/lib/python3.9/site-packages (from requests->cpi) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in /Users/michaelsmith/opt/anaconda3/lib/python3.9/site-packages (from requests->cpi) (2021.10.8)
Requirement already satisfied: idna<3,>=2.5 in /Users/michaelsmith/opt/anaconda3/lib/python3.9/site-packages (from requests->cpi) (2.10)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /Users/michaelsmith/opt/anaconda3/lib/python3.9/site-packages (from requests->cpi) (1.25.11)
Installing collected packages: cpi
Successfully installed cpi-1.0.5

In [8]:
import pandas as pd
import string, re
import cpi

In [26]:
final_movies_combined[final_movies_combined['Year'] <= 2021]

,Rank,Title,Studio,Gross,Year,Words,Word Counts,adjusted_gross
0,1,The Jazz Singer,Warner Bros.,1974000,1927,"{'know': 13, 'mammy': 13, 'singing': 12, 'litt...",155,3.074108e+07
1,8,The Terror,Warner Bros.,1221000,1928,"{'baby': 15, 'crying': 10, 'gasping': 10, 'che...",94,1.934821e+07
2,1,The Broadway Melody,Metro-Goldwyn-Mayer,2808000,1929,"{'oh': 134, 'get': 84, 'queenie': 75, 'go': 74...",477,4.449613e+07
3,1,Whoopee!,United Artists/Samuel Goldwyn Productions,2655000,1930,"{'henry': 71, 'know': 64, 'oh': 62, 'get': 61,...",605,4.307936e+07
4,3,All Quiet on the Western Front,Universal Pictures,1634000,1930,"{'come': 57, 'left': 55, 'get': 38, 'right': 3...",404,2.651287e+07
...,...,...,...,...,...,...,...,...
867,29,"My Country, My Parents",China Lion Film Distribution,221701823,2021,"{'dad': 100, 'go': 57, 'mom': 55, 'father': 47...",823,NaN
868,30,Jungle Cruise,Disney,220889446,2021,"{'frank': 95, 'oh': 74, 'know': 49, 'go': 49, ...",625,NaN
869,5,The King and I,20th Century Fox,8500000,1956,"{'majesty': 94, 'king': 85, 'shall': 81, 'anna...",742,NaN
870,2,The Egg and I,Universal Pictures,5500000,1947,"{'oh': 133, 'get': 84, 'like': 64, 'got': 62, ...",689,NaN
871,8,The Quiet Man,Republic Pictures,3800000,1952,"{'good': 52, 'thornton': 50, 'man': 46, 'come'...",586,NaN

In [27]:
final_movies_combined = pd.read_json('./data/final_movies_combined.json')
def calc_infl(f_id, gross, year):
    adjusted = cpi.inflate(gross, year)
    final_movies_combined.loc[final_movies_combined.index[f_id], 'adjusted'] = adjusted

# final_movies_combined.apply(lambda x: calc_infl(x.name, int(x['Gross']), int(x['Year'])), axis=1)
# df['col_3'] = df.apply(lambda x: f(x.col_1, x.col_2), axis=1)
final_movies_combined['adjusted_gross'] = final_movies_combined[final_movies_combined['Year'] <= 2021].apply(lambda x: cpi.inflate(x['Gross'], x['Year']), axis=1) 
# adjusted = cpi.inflate(30000, 1950)
# adjusted
final_movies_combined

,Rank,Title,Studio,Gross,Year,Words,Word Counts,adjusted_gross
0,1,The Jazz Singer,Warner Bros.,1974000,1927,"{'know': 13, 'mammy': 13, 'singing': 12, 'litt...",155,3.074108e+07
1,8,The Terror,Warner Bros.,1221000,1928,"{'baby': 15, 'crying': 10, 'gasping': 10, 'che...",94,1.934821e+07
2,1,The Broadway Melody,Metro-Goldwyn-Mayer,2808000,1929,"{'oh': 134, 'get': 84, 'queenie': 75, 'go': 74...",477,4.449613e+07
3,1,Whoopee!,United Artists/Samuel Goldwyn Productions,2655000,1930,"{'henry': 71, 'know': 64, 'oh': 62, 'get': 61,...",605,4.307936e+07
4,3,All Quiet on the Western Front,Universal Pictures,1634000,1930,"{'come': 57, 'left': 55, 'get': 38, 'right': 3...",404,2.651287e+07
...,...,...,...,...,...,...,...,...
867,29,"My Country, My Parents",China Lion Film Distribution,221701823,2021,"{'dad': 100, 'go': 57, 'mom': 55, 'father': 47...",823,2.217018e+08
868,30,Jungle Cruise,Disney,220889446,2021,"{'frank': 95, 'oh': 74, 'know': 49, 'go': 49, ...",625,2.208894e+08
869,5,The King and I,20th Century Fox,8500000,1956,"{'majesty': 94, 'king': 85, 'shall': 81, 'anna...",742,8.467812e+07
870,2,The Egg and I,Universal Pictures,5500000,1947,"{'oh': 133, 'get': 84, 'like': 64, 'got': 62, ...",689,6.683117e+07
871,8,The Quiet Man,Republic Pictures,3800000,1952,"{'good': 52, 'thornton': 50, 'man': 46, 'come'...",586,3.885608e+07

In [28]:
final_movies_combined.to_json('final_movies_combined_adjusted.json', orient='records')